spring:
  config:
    activate:
      on-profile: local

  data:
    mongodb:
      host: localhost:27017
      database: award-factory-alpha
      uri: mongodb://localhost:27017/

    redis:
      host: localhost
      port: 6379