version: "3"

services:
  npm:
    container_name: npm
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - .docker/data:/data
      - .docker/letsencrypt:/etc/letsencrypt
    networks:
      - award_maker_network
  #
  #
  #
  # database:
  #   container_name: milipat/database/mysql
  #   image: mysql
  #   restart: unless-stopped
  #   volumes:
  #     - .docker/data/database/mysql:/var/lib/mysql
  #   ports:
  #     - 3306:3306
  #   environment:
  #     - MYSQL_DATABASE=db_Dev
  #     - MYSQL_ROOT_PASSWORD=1234
  #     # - MYSQL_ROOT_USER=root
  #     # - MYSQL_PASSWORD
  #     - TZ=Asiz/Seoul
  #   networks:
  #     - award_maker_network
  #
  #
  #
  backend:
    container_name: backend
    platform: linux/amd64
    build:
      context: ./be/
      dockerfile: Dockerfile
    # depends_on:
    #   - database
    restart: on-failure
    ports:
      - 8081:8081
    networks:
      - award_maker_network
  #
  #
  #
  # frontend:
  #   container_name: frontend
  #   platform: linux/amd64
  #   build:
  #     context: ./fe/
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - backend
  #   restart: on-failure
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - award_maker_network
  #
networks:
  award_maker_network:
    driver: bridge
    external: true
