services:
  npm:
    container_name: npm
    image: "jc21/nginx-proxy-manager:latest"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - .docker/data:/data
      - .docker/letsencrypt:/etc/letsencrypt
    networks:
      - award_factory_network
  #
  frontend:
    container_name: frontend
    platform: linux/amd64
    build:
      context: ./fe/
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 3000:3000
    networks:
      - award_factory_network
  #
  be:
    container_name: be
    platform: linux/amd64
    build:
      context: ./be/
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - award_factory_network

networks:
  award_factory_network:
    # driver: bridge
    # external: false
