FROM python:3.10

WORKDIR /code

COPY ./requirements.txt /code/requirements.txt

RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu124

RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

COPY . /code

RUN python /code/setup.py

CMD ["fastapi", "run", "main.py", "--port", "80"]